<?php
/**
 * @var \DataCue\MagentoModule\Widget\Banner $block
 */
?>
<?php if($block->getData('img') && $block->getData('link')): ?>
  <link rel="stylesheet" type="text/css" href="<?php echo $block->getCustomCssURL() ?>" />
  <div
    data-dc-banners
    data-dc-static-img="<?php echo $block->getData('img'); ?>"
    data-dc-static-link="<?php echo $block->getData('link'); ?>"></div>
<?php endif; ?>
