<script>
window.datacueURLs = {
  getApiKeyAndApiSecret: '<?php echo $this->getUrl('datacue_magento/setting/getApiKeyAndApiSecret'); ?>',
  setApiKeyAndApiSecret: '<?php echo $this->getUrl('datacue_magento/setting/setApiKeyAndApiSecret'); ?>',
  getWebsiteList: '<?php echo $this->getUrl('datacue_magento/setting/getWebsiteList'); ?>',
  getCustomCss: '<?php echo $this->getUrl('datacue_magento/customCss/index'); ?>',
  setCustomCss: '<?php echo $this->getUrl('datacue_magento/customCss/save'); ?>',
  getLogDateList: '<?php echo $this->getUrl('datacue_magento/log/dateList'); ?>',
  getLogView: '<?php echo $this->getUrl('datacue_magento/log/view'); ?>',
  getSyncStatus: '<?php echo $this->getUrl('datacue_magento/sync/status'); ?>',
  disconnect: '<?php echo $this->getUrl('datacue_magento/setting/disconnect'); ?>',
  getRecommendations: '<?php echo $this->getUrl('datacue_magento/recommendation/index'); ?>',
  setRecommendations: '<?php echo $this->getUrl('datacue_magento/recommendation/save'); ?>'
};
</script>
<div id="datacue-app"></div>
