<?php
/**
 * @var \Datacue\MagentoModule\AdminPage\Setting $block
 */
$apiKey = $block->getApiKey();
$apiSecret = $block->getApiSecret();
?>
<div id="datacue-tabs">
  <ul>
    <li><a href="#tabs-1">Settings</a></li>
    <li><a href="#tabs-2">Sync Status</a></li>
    <li><a href="#tabs-3">Logs</a></li>
  </ul>
  <div id="tabs-1">
    <form style="font-size: 20px;" method="post" action="<?php echo $this->getUrl('datacue_magento/setting/save'); ?>">
      <div style="margin: 10px 0;">
        <label for="api_key" style="display: inline-block; width: 100px; text-align: right;">API key</label>
        <input id="api_key" name="api_key" style="width: 300px;" value="<?php echo $apiKey ?>" />
      </div>
      <div style="margin: 10px 0;">
        <label for="api_secret" style="display: inline-block; width: 100px; text-align: right;">API secret</label>
        <input id="api_secret" name="api_secret" type="password" style="width: 300px;" value="<?php echo $apiSecret ?>" />
      </div>
      <input name="form_key" type="hidden" value="<?php /** @escapeNotVerified */ echo $this->getFormKey() ?>" />
      <button class="ui-button ui-widget ui-corner-all" style="font-size: .8em; margin-left: 105px;">Save</button>
    </form>
    <div style="margin-top: 10px; padding-top: 20px; border-top: 1px solid #aaa;">
      <a href="https://app.datacue.co" target="_blank" style="display: inline-block; text-decoration:none; background-color: #80ab4b; color: #fff; padding: 0 20px; height: 40px; border-radius: 20px; line-height: 40px; text-align: center;">LOGIN TO MY DATACUE DASHBOARD</a>
      <div style="margin-top: 20px; font-size: 15px;">No account yet? Sign up <a href="https://app.datacue.co/en/sign-up" target="_blank" style="color: #8c5c85; font-weight: 600;">here</a></div>
    </div>
  </div>
  <div id="tabs-2">
    <table id="datacue-sync-status-table">
      <thead>
      <tr>
        <th width="100">Data Type</th>
        <th width="100">Total</th>
        <th width="100">Number of pending</th>
        <th width="100">Number of successes</th>
        <th width="100">Number of failures</th>
      </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
  <div id="tabs-3">
    <?php
      // Dates
      $dates = '<select id="datacue-logs-date-select">';
      $timestamp = time();
      for ($i = 0; $i < 3; $i++) {
          $date = date('Y-m-d', $timestamp);
          if (file_exists(__DIR__ . "/../../../datacue-$date.log")) {
              $dates .= "<option value=\"$date\"" . ($i === 0 ? ' selected' : '') . ">$date</option>";
          }
          $timestamp -= 24 * 3600;
      }
      $dates .= '</select>';
      echo $dates;
    ?>
    <iframe id="datacue-log-frame" src="" style="width: 100%; height: 500px; border: 0.5px solid #eee; margin-top: 5px;"></iframe>
  </div>
</div>
<script>
  function getSyncStatus ($) {
    $.ajax({
      showLoader: true,
      url: '<?php echo $this->getUrl('datacue_magento/sync/status'); ?>',
      type: "POST",
      data: {
        form_key: FORM_KEY
      },
      dataType: 'json'
    }).done(function (data) {
      console.log('ajax', data);
      var html = '';
      Object.keys(data).forEach(function (key) {
        html += '<tr>';
        html += '<td align="center">' + key + '</td>';
        html += '<td align="center">' + data[key].total + '</td>';
        html += '<td align="center">' + (data[key].total - data[key].completed - data[key].failed) + '</td>';
        html += '<td align="center">' + data[key].completed + '</td>';
        html += '<td align="center">' + data[key].failed + '</td>';
        html += '</tr>';
      });
      $("#datacue-sync-status-table tbody").html(html);
    });
  };
  function getLogOfDate($, date) {
    $("#datacue-log-frame").attr('src', '<?php echo $this->getUrl('datacue_magento/log/view'); ?>?date=' + date);
  }
  require([
    'jquery',
    'jquery/ui'
  ], function($) {
    $("#datacue-tabs").tabs();
    getSyncStatus($);
    setInterval(function () {
      getSyncStatus($);
    }, 30000);

    var currentDate = jQuery("#datacue-logs-date-select").val();
    if (currentDate && currentDate != '') {
      getLogOfDate($, currentDate);
    }
    $("#datacue-logs-date-select").change(function() {
      getLogOfDate($, $("#datacue-logs-date-select").val());
    });
  });
</script>